# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: party-anniversary
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080