name: Deploy

on:
  workflow_run:
    workflows: ["Build and push"]
    types: [completed]
  workflow_dispatch: 
  

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Deploy ⚡"
    runs-on: ubuntu-latest
    steps:
      - name: Wait for current deployment
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          abort-after-seconds: 300
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Pull updated images
        run: ssh server 'docker-compose pull'

      - name: Launch updated container
        if: ${{ always() }}
        run: ssh server 'docker-compose up -d --no-deps --build backend'

      - name: Clean old images
        run: ssh server 'sleep 300; docker image prune -f'